"""empty message

Revision ID: 4e1894be1cca
Revises: 8593f77d68a3
Create Date: 2022-09-21 16:13:06.405648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e1894be1cca'
down_revision = '8593f77d68a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_to_triptype')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_to_triptype',
    sa.Column('trip_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('trip_type_id', sa.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['trip_type_id'], ['triptypes.id'], ),
    sa.PrimaryKeyConstraint('trip_id', 'trip_type_id')
    )
    # ### end Alembic commands ###
